steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/amikus/helloworld/helloapp:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/amikus/helloworld/helloapp:latest'
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update-container', 'instance-1', '--zone', 'asia-south1-c', '--container-image', 'asia-south1-docker.pkg.dev/amikus/helloworld/helloapp:latest']

options:
  logging: CLOUD_LOGGING_ONLY
  
images:
  - 'asia-south1-docker.pkg.dev/amikus/helloworld/helloapp:latest'

