steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/amikus/helloworld:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/amikus/helloworld:$COMMIT_SHA'

images:
  - 'asia-south1-docker.pkg.dev/amikus/helloworld:$COMMIT_SHA'
